### ISSUE TITLE
Add fee to payment line item to price breakdown

### ISSUE THREAD

**Issue by evawhateva** [OmInformationTechnology/omitfoundation#11]
Make sure the paypal fee is enumerated on the price breakdown screen on membership page.

**Comment by thevermeer** [comment]
Are there a full set of instructions for how to do this?

**Comment by thevermeer** [comment]
Rather, Dale ought not have to write copy - can we please have the specifics outlined? How much are the paypal fees? Are they being added to the price? 

How you spoken with Dale about how this will look?

**Comment by Soren-Nordstrom** [comment]
I'll get this done tomorrow.

**Comment by Soren-Nordstrom** [comment]
Added a line reflecting PayPal fees.
