### ISSUE TITLE
update homepage banners

### ISSUE THREAD

**Issue by Soren-Nordstrom** [OmInformationTechnology/omitfoundation#4]
solstice-banner-large.gif, solstice-banner-medium.gif, solstice-banner.jpg need to be updated to the proper date.

**Comment by evawhateva** [comment]
![solsticeheader_1920x400_va1-0_11f-2016-mar16](https://cloud.githubusercontent.com/assets/17887177/13933068/c054d350-ef81-11e5-8923-fd3a42d408ed.gif)

**Comment by Soren-Nordstrom** [comment]
Banners updated.  Closing.
